version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
    command: tail -f /dev/null
  mongo:
    image: mongo:3.6
    ports:
      - 27018:27017
    command: --nojournal --setParameter enableTestCommands=true